### PR TITLE
Fix the broken link of KubeSphere LOGO

### LINKED ISSUE #6: Broken logo link of the DevOps scenario
image

/good-first-issue

### PR DESCRIPTION
**Pull request by yJunS**
Fix #6

### CODE REVIEW

**Review by AbdelouahabMbarki — CHANGES_REQUESTED** [review]
thank you  Nice Job ,  I think it will be more awesome to put kubesphere-logo.png in the repository main asset folder (katacoda-scenarios/assets/) so all the scenarios can Request it from there

**Comment by yJunS** [comment]
> thank you Nice Job , I think it will be more awesome to put kubesphere-logo.png in the repository main asset folder (katacoda-scenarios/assets/) so all the scenarios can Request it from there

I already moved it and updated the link.

**Comment by LinuxSuRen** [comment]
> I already moved it and updated the link.

move or copy? I prefer to move them instead of coping.

**Comment by yJunS** [comment]
> > I already moved it and updated the link.
> 
> move or copy? I prefer to move them instead of coping.

Oh. My bad. I already moved it.

**Review by AbdelouahabMbarki — APPROVED** [review]
LGTM

**Review by LinuxSuRen — COMMENTED** [review]
/lgtm

**Pull request merged**
